import { ThemeColors, ColorTheme } from "./types";

export const colorThemes: Record<ColorTheme, ThemeColors> = {
  blue: {
    name: "Blue",
    primary: "bg-blue-600 hover:bg-blue-700",
    primaryLight: "bg-blue-500 hover:bg-blue-600",
    primaryBorder: "border-blue-500",
    primaryRing: "ring-blue-500",
    primaryFocus: "focus:border-blue-500",
    heading: "text-blue-400",
    headingLight: "text-blue-600",
    value: "text-blue-300",
    valueLight: "text-blue-600",
    highlight: "bg-blue-500/20 border-l-blue-500",
  },
  emerald: {
    name: "Emerald",
    primary: "bg-emerald-600 hover:bg-emerald-700",
    primaryLight: "bg-emerald-500 hover:bg-emerald-600",
    primaryBorder: "border-emerald-500",
    primaryRing: "ring-emerald-500",
    primaryFocus: "focus:border-emerald-500",
    heading: "text-emerald-400",
    headingLight: "text-emerald-600",
    value: "text-emerald-300",
    valueLight: "text-emerald-600",
    highlight: "bg-emerald-500/20 border-l-emerald-500",
  },
  purple: {
    name: "Purple",
    primary: "bg-purple-600 hover:bg-purple-700",
    primaryLight: "bg-purple-500 hover:bg-purple-600",
    primaryBorder: "border-purple-500",
    primaryRing: "ring-purple-500",
    primaryFocus: "focus:border-purple-500",
    heading: "text-purple-400",
    headingLight: "text-purple-600",
    value: "text-purple-300",
    valueLight: "text-purple-600",
    highlight: "bg-purple-500/20 border-l-purple-500",
  },
  cyan: {
    name: "Cyan",
    primary: "bg-cyan-600 hover:bg-cyan-700",
    primaryLight: "bg-cyan-500 hover:bg-cyan-600",
    primaryBorder: "border-cyan-500",
    primaryRing: "ring-cyan-500",
    primaryFocus: "focus:border-cyan-500",
    heading: "text-cyan-400",
    headingLight: "text-cyan-600",
    value: "text-cyan-300",
    valueLight: "text-cyan-600",
    highlight: "bg-cyan-500/20 border-l-cyan-500",
  },
  orange: {
    name: "Orange",
    primary: "bg-orange-600 hover:bg-orange-700",
    primaryLight: "bg-orange-500 hover:bg-orange-600",
    primaryBorder: "border-orange-500",
    primaryRing: "ring-orange-500",
    primaryFocus: "focus:border-orange-500",
    heading: "text-orange-400",
    headingLight: "text-orange-600",
    value: "text-orange-300",
    valueLight: "text-orange-600",
    highlight: "bg-orange-500/20 border-l-orange-500",
  },
  rose: {
    name: "Rose",
    primary: "bg-rose-600 hover:bg-rose-700",
    primaryLight: "bg-rose-500 hover:bg-rose-600",
    primaryBorder: "border-rose-500",
    primaryRing: "ring-rose-500",
    primaryFocus: "focus:border-rose-500",
    heading: "text-rose-400",
    headingLight: "text-rose-600",
    value: "text-rose-300",
    valueLight: "text-rose-600",
    highlight: "bg-rose-500/20 border-l-rose-500",
  },
  indigo: {
    name: "Indigo",
    primary: "bg-indigo-600 hover:bg-indigo-700",
    primaryLight: "bg-indigo-500 hover:bg-indigo-600",
    primaryBorder: "border-indigo-500",
    primaryRing: "ring-indigo-500",
    primaryFocus: "focus:border-indigo-500",
    heading: "text-indigo-400",
    headingLight: "text-indigo-600",
    value: "text-indigo-300",
    valueLight: "text-indigo-600",
    highlight: "bg-indigo-500/20 border-l-indigo-500",
  },
};
